### ISSUE TITLE
auth (here we go againnnn)

### ISSUE THREAD

**Issue by faultables** [evilfactorylabsarchive/pembayaran#1]
## Deskripsi

Yowww sebagai pengguna saya ingin bisa menggunakan aplikasi ini kan, nah langkah pertama yang harus dilakuin biasanya otententikasi, jadi, ya, bikin itu dulu

Versi di project ini sederhana aja, cuma butuh nama; email (dibutuhin sama PG), dan kata sandi (bcrypt), terus untuk otorisasi pakai jwt karena gw males fullstack

- forgot password gak dulu lah ya
- verifikasi email juga gak usah dulu, kan gw doang yang pakai dan gw bukan bot

test cases:

- login pakai email + password
- hasil dari login adalah jwt token dengan payload id + nama + email + role
- klo kombinasi email/password ga sesuai, kirim status 401 (basic lah ya)

## Beban

- Kemungkinan 3 jam
- +1 jam buat nulis test

**Comment by rafiramadhana** [comment]
Hi, met pagy ☀️.
Kemungkinan saya bisa bantu, tapi kalo boleh tau, akan ditulis dalam bahasa apa ya auth-nya?
Sebagai tambahan, saya juga belum tau untuk project ini arsitekturnya akan seperti apa, jika ada informasi terkait itu, akan membantu.
Terima kasih!

**Comment by faultables** [comment]
Hi, met siyang ☀️

Terima kasih untuk ketertarikannya! Sebagai gambaran, untuk backend nya kita akan menggunakan... Postgres?

Nah, untuk membahas lebih lanjut, bisa bergabung ke discord nya [evilfactorylabs](https://evlfctry.pro/discord) nanti kita akan ngobrolin ini disana. Klo di jam kerja mungkin lumayan slow response but will do my best!

**Comment by rafiramadhana** [comment]
Ok, anytime and thanks for the response, saya sudah bergabung. 
Anyway, izin untuk mengetuk kanal #umum 🙏.

**Comment by faultables** [comment]
Closed by #2
